import { Container, Table } from "react-bootstrap";

function Routine({ routine }) {
	
	//this function is really bad, please don't look inside! im too lazy to optimize this, maybe one day!
	//TODO: optimize this!!!
	const arr = [0,1,2,3,4,5]
	// const days = ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"]
	const createTable = () => (
		<Container>
				<Table bordered responsive className="my-table">
					<tr>
						<th></th>
						<th>08:30-10:00</th>
						<th>10:00-11:30</th>
						<th>11.30-01:00</th>
						<th>01:00-02:30</th>
						<th>02:30-04:00</th>
						<th>04:00-05:30</th>
					</tr>

					<tr>
						<td><b>Saturday</b></td>
						{arr.map((index) => (<>{routine.map((r) => (<td>{r.Saturday[index].map((c) => (<>{c.course_code}</>))}</td>))}</>))}
					</tr>

					<tr>
						<td><b>Sunday</b></td>
						{arr.map((index) => (<>{routine.map((r) => (<td>{r.Sunday[index].map((c) => (<>{c.course_code}</>))}</td>))}</>))}
					</tr>

					<tr>
						<td><b>Monday</b></td>
						{arr.map((index) => (<>{routine.map((r) => (<td>{r.Monday[index].map((c) => (<>{c.course_code}</>))}</td>))}</>))}
					</tr>

					<tr>
						<td><b>Tuesday</b></td>
						{arr.map((index) => (<>{routine.map((r) => (<td>{r.Tuesday[index].map((c) => (<>{c.course_code}</>))}</td>))}</>))}
					</tr>

					<tr>
						<td><b>Wednesday</b></td>
						{arr.map((index) => (<>{routine.map((r) => (<td>{r.Wednesday[index].map((c) => (<>{c.course_code}</>))}</td>))}</>))}
					</tr>

					<tr>
						<td><b>Thursday</b></td>
						{arr.map((index) => (<>{routine.map((r) => (<td>{r.Thursday[index].map((c) => (<>{c.course_code}</>))}</td>))}</>))}
					</tr>
				</Table>
				<p className="text-muted table-caption">Generated by <a href="https://cr2.netlify.app">https://cr2.netlify.app</a></p>
				<p className="text-muted table-caption">Disclaimer: This is a testing version, please double check the routine before following it. We will not be responsible for any issue this may cause. Please report any bugs using the Contact menu.</p>
		</Container>
	);

	//check if routine obj is empty or not, returns bool
	const isEmpty = (routine) => {
		if (routine === null) {
			return true;
		} else {
			return false;
		}
	};

	return (
		<div>
			{/* if empty show nothing otherwise show routine */}
			{isEmpty(routine) ? <></> : <>{createTable()}</>}
		</div>
	);
}

export default Routine;
